language: python
os:
        - linux
rvm:
        - 3.6
install:
        - pip install python-coveralls
        - pip install coverage
script:
        - coverage run ./tests.py
after_success:
        - coveralls
